src/Entity/UserDetails.php
<?php

namespace App\Entity;

use Doctrine\ORM\Mapping as ORM;

/**
 * @ORM\Entity(repositoryClass="App\Repository\UserDetailsRepository")
 */
class UserDetails
{
    /**
     * @ORM\Id()
     * @ORM\GeneratedValue()
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="integer")
     */
    private $user_is;

    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     */
    private $address;

    /**
     * @ORM\Column(type="string", length=100, nullable=true)
     */
    private $name;

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getUserIs(): ?int
    {
        return $this->user_is;
    }

    public function setUserIs(int $user_is): self
    {
        $this->user_is = $user_is;

        return $this;
    }

    public function getAddress(): ?string
    {
        return $this->address;
    }

    public function setAddress(?string $address): self
    {
        $this->address = $address;

        return $this;
    }

    public function getName(): ?string
    {
        return $this->name;
    }

    public function setName(?string $name): self
    {
        $this->name = $name;

        return $this;
    }
}

src/Form/UserDetailsType.php
<?php

namespace App\Form;

use App\Entity\UserDetails;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;

class UserDetailsType extends AbstractType
{
    public function buildForm(FormBuilderInterface $builder, array $options)
    {
        $builder
            ->add('user_is')
            ->add('address')
            ->add('name')
        ;
    }

    public function configureOptions(OptionsResolver $resolver)
    {
        $resolver->setDefaults([
            'data_class' => UserDetails::class,
        ]);
    }
}

src/Controller/UserDetailsController.php
<?php

namespace App\Controller;

use App\Entity\UserDetails;
use App\Form\UserDetailsType;
use App\Repository\UserDetailsRepository;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;

/**
 * @Route("/user/details")
 */
class UserDetailsController extends AbstractController
{
    /**
     * @Route("/", name="user_details_index", methods={"GET"})
     */
    public function index(UserDetailsRepository $userDetailsRepository): Response
    {
        return $this->render('user_details/index.html.twig', [
            'user_details' => $userDetailsRepository->findAll(),
        ]);
    }

    /**
     * @Route("/new", name="user_details_new", methods={"GET","POST"})
     */
    public function new(Request $request): Response
    {
        $userDetail = new UserDetails();
        $form = $this->createForm(UserDetailsType::class, $userDetail);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $entityManager = $this->getDoctrine()->getManager();
            $entityManager->persist($userDetail);
            $entityManager->flush();

            return $this->redirectToRoute('user_details_index');
        }

        return $this->render('user_details/new.html.twig', [
            'user_detail' => $userDetail,
            'form' => $form->createView(),
        ]);
    }

    /**
     * @Route("/{id}", name="user_details_show", methods={"GET"})
     */
    public function show(UserDetails $userDetail): Response
    {
        return $this->render('user_details/show.html.twig', [
            'user_detail' => $userDetail,
        ]);
    }

    /**
     * @Route("/{id}/edit", name="user_details_edit", methods={"GET","POST"})
     */
    public function edit(Request $request, UserDetails $userDetail): Response
    {
        $form = $this->createForm(UserDetailsType::class, $userDetail);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $this->getDoctrine()->getManager()->flush();

            return $this->redirectToRoute('user_details_index');
        }

        return $this->render('user_details/edit.html.twig', [
            'user_detail' => $userDetail,
            'form' => $form->createView(),
        ]);
    }

    /**
     * @Route("/{id}", name="user_details_delete", methods={"DELETE"})
     */
    public function delete(Request $request, UserDetails $userDetail): Response
    {
        if ($this->isCsrfTokenValid('delete'.$userDetail->getId(), $request->request->get('_token'))) {
            $entityManager = $this->getDoctrine()->getManager();
            $entityManager->remove($userDetail);
            $entityManager->flush();
        }

        return $this->redirectToRoute('user_details_index');
    }
}

templates/user_details/_delete_form.html.twig
<form method="post" action="{{ path('user_details_delete', {'id': user_detail.id}) }}" onsubmit="return confirm('Are you sure you want to delete this item?');">
    <input type="hidden" name="_method" value="DELETE">
    <input type="hidden" name="_token" value="{{ csrf_token('delete' ~ user_detail.id) }}">
    <button class="btn">Delete</button>
</form>

templates/user_details/_form.html.twig
{{ form_start(form) }}
    {{ form_widget(form) }}
    <button class="btn">{{ button_label|default('Save') }}</button>
{{ form_end(form) }}

templates/user_details/edit.html.twig
{% extends 'base.html.twig' %}

{% block title %}Edit UserDetails{% endblock %}

{% block body %}
    <h1>Edit UserDetails</h1>

    {{ include('user_details/_form.html.twig', {'button_label': 'Update'}) }}

    <a href="{{ path('user_details_index') }}">back to list</a>

    {{ include('user_details/_delete_form.html.twig') }}
{% endblock %}

templates/user_details/index.html.twig
{% extends 'base.html.twig' %}

{% block title %}UserDetails index{% endblock %}

{% block body %}
    <h1>UserDetails index</h1>

    <table class="table">
        <thead>
            <tr>
                <th>Id</th>
                <th>User_is</th>
                <th>Address</th>
                <th>Name</th>
                <th>actions</th>
            </tr>
        </thead>
        <tbody>
        {% for user_detail in user_details %}
            <tr>
                <td>{{ user_detail.id }}</td>
                <td>{{ user_detail.userIs }}</td>
                <td>{{ user_detail.address }}</td>
                <td>{{ user_detail.name }}</td>
                <td>
                    <a href="{{ path('user_details_show', {'id': user_detail.id}) }}">show</a>
                    <a href="{{ path('user_details_edit', {'id': user_detail.id}) }}">edit</a>
                </td>
            </tr>
        {% else %}
            <tr>
                <td colspan="5">no records found</td>
            </tr>
        {% endfor %}
        </tbody>
    </table>

    <a href="{{ path('user_details_new') }}">Create new</a>
{% endblock %}

templates/user_details/new.html.twig
{% extends 'base.html.twig' %}

{% block title %}New UserDetails{% endblock %}

{% block body %}
    <h1>Create new UserDetails</h1>

    {{ include('user_details/_form.html.twig') }}

    <a href="{{ path('user_details_index') }}">back to list</a>
{% endblock %}

templates/user_details/show.html.twig
{% extends 'base.html.twig' %}

{% block title %}UserDetails{% endblock %}

{% block body %}
    <h1>UserDetails</h1>

    <table class="table">
        <tbody>
            <tr>
                <th>Id</th>
                <td>{{ user_detail.id }}</td>
            </tr>
            <tr>
                <th>User_is</th>
                <td>{{ user_detail.userIs }}</td>
            </tr>
            <tr>
                <th>Address</th>
                <td>{{ user_detail.address }}</td>
            </tr>
            <tr>
                <th>Name</th>
                <td>{{ user_detail.name }}</td>
            </tr>
        </tbody>
    </table>

    <a href="{{ path('user_details_index') }}">back to list</a>

    <a href="{{ path('user_details_edit', {'id': user_detail.id}) }}">edit</a>

    {{ include('user_details/_delete_form.html.twig') }}
{% endblock %}